baseURL = "https://www.tablaustad.com/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Tabla Ustad"
canonifyurls = true
publishDir = "docs"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1

[[menu.main]]
name = "Videos"
url = "#blog"
weight = 6

[[menu.main]]
name = "Contact"
url = "contact"
weight = 7

[[menu.main]]
name = "About"
url = "#about"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "Facebook"
url = "https://www.facebook.com/tablaclasses/"
weight = 1
[[menu.sitemap]]
name = "Youtube"
url = "http://www.youtube.com/c/BhagawanSingh%20"
weight = 2

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "Copyright Â© 2021, S B Singh. All Right Reserved."
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Sb Singh Tabla Class Academy, \n Gardenia Jasminoides, 2nd Cross Rd, Lakshmaiah Layout, Horamavu, Bengaluru, Karnataka"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+918884283969"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/tablaclasses/"
weight = 1
[[params.social]]
icon = "fa-youtube-square"
url = "https://www.youtube.com/c/BhagawanSingh/videos"
weight = 2
